# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-16 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('blo', models.CharField(max_length=1000)),
            ],
        ),
    ]
